### ISSUE TITLE
sample-config option wants to write to /etc

### ISSUE THREAD

**Issue by kaoru** [kohts/snaked#1]
Is it necessary that the snaked configuration lives in /etc/ rather than an arbitrary directory?

I think the default should be ./etc/ so that it can run entirely without root access.

**Comment by kohts** [comment]
It doesn't root, check out --cfg option

**Comment by kohts** [comment]
Doesn't need

**Comment by kohts** [comment]
Basically run 'snaked --sample-config /some/path' and then 'snaked --cfg /some/path'

**Comment by kohts** [comment]
Second command should read as 'snaked --cfg /some/patj --debug' or replave debug with daemon
